# Generated by Django 5.0.6 on 2026-07-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlecredential',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='googlecredential',
            name='token',
        ),
        migrations.AddField(
            model_name='googlecredential',
            name='refresh_token_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='googlecredential',
            name='token_encrypted',
            field=models.TextField(blank=True),
        ),
    ]
