# Generated by Django 5.0.6 on 2026-07-03 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('doc_type', models.CharField(choices=[('CONCEPT_PAPER', 'Concept Paper'), ('PROPOSAL_MANUSCRIPT', 'Proposal Manuscript'), ('FINAL_MANUSCRIPT', 'Final Manuscript'), ('REVISION', 'Revision'), ('OTHER', 'Other')], default='OTHER', max_length=25)),
                ('stage', models.CharField(choices=[('CONCEPT', 'Concept'), ('PROPOSAL', 'Proposal'), ('FINAL', 'Final Defense')], default='CONCEPT', max_length=10)),
                ('drive_file_id', models.CharField(blank=True, max_length=128)),
                ('drive_link', models.URLField(help_text='Google Docs / Drive URL of the document.')),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REVISION', 'Revision Requested'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('feedback', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='groups.thesisgroup')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='documents.thesisdocument')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
